name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: checking
      run: pwd && ls

    - name: Build the Docker image
      run: docker build -f ./app/Dockerfile -t almogso/pokemon-api .


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Push
      run: docker push almogso/pokemon-api
