name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: checking
      run: pwd && ls

    - name: Build the Docker image
      run: docker build -f ./app/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/pokemon-api .


    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Docker Push
      run: docker push almogso/pokemon-api

    - name: export ssh key
      run: echo "${{ secrets.SSH_KEY }}" >> ssh.pem && chmod 400 ssh.pem
      
    - name: Ensure target directory exists
      run: ssh -o StrictHostKeyChecking=no -i ssh.pem ubuntu@18.234.40.30 "mkdir -p /home/ubuntu"

    - name: Copy YAMLs to EC2
      run: scp -o StrictHostKeyChecking=no -i ssh.pem kubernetes/deployment.yaml ubuntu@18.234.40.30:/home/ubuntu/

    - name: Deploy with kubectl
      run: ssh -o StrictHostKeyChecking=no -i ssh.pem ubuntu@18.234.40.30 "kubectl apply -f /home/ubuntu/deployment.yaml"