name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
      
    - name: Build the Docker image
      run: docker build -f .\app\Dockerfile -t almogso/pokemon-api .
